stages:
  - "test"
  - "coverage"
  - "build"

include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

variables:
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle" # cache can only be inside project dir
  GRADLE_CLI_OPTS: "--no-daemon --console=plain" # avoid console spam

default:
  image: "eclipse-temurin:17-alpine"
  cache:
    key: "gradle"
    paths: [ ".gradle/wrapper", ".gradle/caches" ]

test:
  stage: "test"
  script:
    - ./gradlew ${GRADLE_CLI_OPTS} test
  coverage: "/Instruction Coverage: *?([0-9]{1,3}.?[0-9]{0,3})%/"
  artifacts:
    reports:
      junit: [ "build/test-results/test/*.xml" ]
    paths: [ "build/reports/jacoco/test/jacocoTestReport.xml" ]

coverage:
  stage: "coverage"
  image: "haynes/jacoco2cobertura:1.0.7"
  allow_failure: true
  script:
    - python /opt/cover2cover.py build/reports/jacoco/test/jacocoTestReport.xml src/main/kotlin > build/reports/coverage.xml
    - python /opt/source2filename.py build/reports/coverage.xml
  artifacts:
    reports:
      cobertura: "build/reports/coverage.xml"
    paths: [ "build/reports/coverage.xml" ]

build:
  stage: "build"
  script:
    - ./gradlew ${GRADLE_CLI_OPTS} packageUberJarForCurrentOS
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
